default: 00 01 02 03

00:
	mkdir -p dst/00/
	python src/00/hello.py > dst/00/hello.go

01:
	mkdir -p dst/01/
	python src/01/person.py > dst/01/person.go

02:
	mkdir -p dst/02/
	python src/02/go-routine.py > dst/02/goroutine.go

03:
	mkdir -p dst/03/
	python src/03/models.py > dst/03/models.go


clean:
	rm -rf dst
